name = "form-builder-latest"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[vars]
# Add your production environment variables here if needed
# ENCRYPTION_SECRET = "..."


