'use client'

import { useState } from 'react'

interface ImportFormModalProps {
  isOpen: boolean
  onClose: () => void
  onImport: (data: any) => Promise<void>
  loading: boolean
}

export default function ImportFormModal({ isOpen, onClose, onImport, loading }: ImportFormModalProps) {
  const [jsonText, setJsonText] = useState('')
  const [error, setError] = useState('')

  if (!isOpen) return null

  const handleImport = async () => {
    if (!jsonText.trim()) return
    setError('')
    await onImport(jsonText)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white rounded-3xl w-full max-w-2xl shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200">
        <div className="px-8 py-6 border-b border-gray-100 flex justify-between items-center">
          <h3 className="text-xl font-black text-gray-900 tracking-tight">Import Form from JSON</h3>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 transition-colors">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M6 18L18 6M6 6l12 12"></path></svg>
          </button>
        </div>

        <div className="p-8">
          <p className="text-gray-500 font-medium mb-6">
            Paste your form definition JSON below. This will automatically set the title, description, fields, and custom design styles.
          </p>

          <textarea
            className="w-full h-80 p-6 bg-gray-50 border border-gray-200 rounded-2xl font-mono text-sm focus:ring-4 focus:ring-indigo-100 focus:border-indigo-500 transition-all outline-none resize-none"
            placeholder={`{
  "name": "My AI Form",
  "description": "Form generated by AI",
  "fields": [
    { "label": "Full Name", "type": "text", "required": true },
    { "label": "Email", "type": "email", "required": true }
  ],
  "customStyles": {
    "accentColor": "#4f46e5",
    "borderRadius": 12,
    "buttonStyle": "pill"
  }
}`}
            value={jsonText}
            onChange={(e) => setJsonText(e.target.value)}
          />

          {error && (
            <div className="mt-4 p-4 bg-red-50 border-l-4 border-red-500 rounded-xl">
              <p className="text-sm text-red-700 font-bold">{error}</p>
            </div>
          )}

          <div className="mt-8 flex gap-3 justify-end">
            <button
              onClick={onClose}
              className="px-6 py-3 rounded-xl font-bold text-gray-500 hover:bg-gray-50 transition-all active:scale-95"
            >
              Cancel
            </button>
            <button
              onClick={handleImport}
              disabled={loading || !jsonText.trim()}
              className="bg-indigo-600 text-white px-8 py-3 rounded-xl font-bold shadow-lg shadow-indigo-100 hover:bg-indigo-700 hover:-translate-y-0.5 transition-all flex items-center gap-2 active:scale-95 disabled:opacity-50"
            >
              {loading ? (
                <svg className="animate-spin h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
              ) : 'Import & Build Form'}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
